# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: vylsaz
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab-bqn
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension for the BQN language.
python_name: jupyterlab_bqn
repository: https://github.com/vylsaz/jupyterlab-bqn
test: false
viewer_name: ''

